POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/91b6cd9f-600f-44f6-8360-07769d2d2ad3/attendees
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john2@email.com"
}

###
GET http://localhost:3333/events/f400d486-4f7c-4284-ade4-88afa7358226

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###
GET http://localhost:3333/events/f400d486-4f7c-4284-ade4-88afa7358226/attendees?query=john